apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: &{fastdfs-storage}
spec:
  serviceName: fastdfs-storage
  replicas: 1
  template:
    metadata:
      labels:
        app: fastdfs-storage
    spec:
      nodeSelector:
        fastdfs: &{moons}
      terminationGracePeriodSeconds: 10
      containers:
      - name: fastdfs-storage
        image: h3crd-wlan1.chinacloudapp.cn:5000/fastdfs_nginx:v1
        command: ["/bin/bash","/tmp/fdfs_config/start.sh","storage"]
        imagePullPolicy: IfNotPresent
        env:
        - name: TRACKER_SERVER
          value: &{TRACKER_SERVER}
        - name: GROUP_NAME
          value: &{GROUP_NAME}
        - name: PORT
          value: &{PORT}
        - name: TRACKER_NUM
          value: &{TRACKER_NUM}
        - name: STORAGE_NGINX_PORT
          value: &{STORAGE_NGINX_PORT}
        - name: TRACKER_SERVER_SLAVE
          value: &{TRACKER_SERVER_SLAVE}
        - name: GROUP_NUM
          value:
        volumeMounts:
        - name: fdfs-config
          mountPath: /tmp/fdfs_config
        - name: storage0-data
          mountPath: /var/fdfs
      volumes:
      - name: fdfs-config
        configMap:
          name: fdfs-config
      hostNetwork: true
  volumeClaimTemplates:
  - metadata:
      name: storage0-data
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: &{FastDFS_Data}Gi
